apiVersion: apps/v1
kind: Deployment
metadata:
  name: etickets-deployment
spec:
  selector:
    matchLabels:
      app: etickets
  replicas: 2
  template:
    metadata:
      labels:
        app: etickets
    spec:
      containers:
      - name: etickets
        image: tbessidocker/etickets:v3.#{Build.BuildId}#
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 300m
            memory: "100Mi"
          requests:
            cpu: 100m
            memory: "50Mi"
        env:
          - name: ConnectionStrings__DefaultConnectionString
            valueFrom:
              secretKeyRef:
                name: mssql-secret
                key: db-connection-string-secret
              #configMapKeyRef:
               # name: mssql-connection-configmap
                #key: db-connection-string
---
apiVersion: v1
kind: Service
metadata:
  name: etickets-service
spec:
  selector:
    app: etickets
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

